version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: qa
      POSTGRES_USER: qa_user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qa_user"]
      interval: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn qa.wsgi:application -b 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SECRET_KEY: changeme-in-prod
      DJANGO_DEBUG: "False"
      POSTGRES_DB: qa
      POSTGRES_USER: qa_user
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    ports:
      - "8000:8000"

volumes:
  postgres_data:
